#!/bin/bash

# Script para criar a estrutura visual do projeto

echo "📂 Estrutura do Projeto - Sistema Financeiro Familiar"
echo "======================================================"
echo ""
echo "Financeiro_2026/"
echo "├── 📁 backend/"
echo "│   ├── src/"
echo "│   │   ├── controllers/          (6 controladores)"
echo "│   │   │   ├── authController.js"
echo "│   │   │   ├── dashboardController.js"
echo "│   │   │   ├── transactionController.js"
echo "│   │   │   ├── creditCardController.js"
echo "│   │   │   ├── investmentController.js"
echo "│   │   │   └── goalsController.js"
echo "│   │   ├── services/             (6 serviços)"
echo "│   │   │   ├── authService.js"
echo "│   │   │   ├── dashboardService.js"
echo "│   │   │   ├── transactionService.js"
echo "│   │   │   ├── creditCardService.js"
echo "│   │   │   ├── investmentService.js"
echo "│   │   │   └── goalsService.js"
echo "│   │   ├── routes/               (6 rotas)"
echo "│   │   │   ├── authRoutes.js"
echo "│   │   │   ├── dashboardRoutes.js"
echo "│   │   │   ├── transactionRoutes.js"
echo "│   │   │   ├── creditCardRoutes.js"
echo "│   │   │   ├── investmentRoutes.js"
echo "│   │   │   └── goalsRoutes.js"
echo "│   │   ├── middleware/           (4 middlewares)"
echo "│   │   │   ├── jwt.js"
echo "│   │   │   ├── auth.js"
echo "│   │   │   ├── rateLimiter.js"
echo "│   │   │   └── errorHandler.js"
echo "│   │   ├── database/             (3 arquivos)"
echo "│   │   │   ├── connection.js"
echo "│   │   │   ├── schema.sql"
echo "│   │   │   └── seed.js"
echo "│   │   └── index.js              (Servidor principal)"
echo "│   ├── package.json"
echo "│   ├── .env (gerado automaticamente)"
echo "│   └── .gitignore"
echo ""
echo "├── 📁 frontend/"
echo "│   ├── src/"
echo "│   │   ├── pages/                (5 páginas)"
echo "│   │   │   ├── LoginPage.jsx"
echo "│   │   │   ├── DashboardPage.jsx"
echo "│   │   │   ├── TransactionsPage.jsx"
echo "│   │   │   ├── CreditCardsPage.jsx"
echo "│   │   │   ├── InvestmentsPage.jsx"
echo "│   │   │   └── GoalsPage.jsx"
echo "│   │   ├── components/           (3 componentes)"
echo "│   │   │   ├── Layout.jsx        (Sidebar + MainLayout)"
echo "│   │   │   ├── PrivateRoute.jsx"
echo "│   │   │   └── (espaço para mais componentes)"
echo "│   │   ├── services/"
echo "│   │   │   ├── api.js            (Cliente Axios)"
echo "│   │   │   └── index.js          (Métodos da API)"
echo "│   │   ├── contexts/"
echo "│   │   │   └── AuthContext.jsx   (Autenticação)"
echo "│   │   ├── utils/                (utilitários futuros)"
echo "│   │   ├── App.jsx               (Router principal)"
echo "│   │   ├── main.jsx              (Entrada)"
echo "│   │   └── index.css             (Estilos)"
echo "│   ├── index.html"
echo "│   ├── vite.config.js"
echo "│   ├── package.json"
echo "│   ├── .env (gerado automaticamente)"
echo "│   └── .gitignore"
echo ""
echo "├── 📁 docker/"
echo "│   ├── Dockerfile.backend        (Multi-stage)"
echo "│   ├── Dockerfile.frontend       (Multi-stage)"
echo "│   └── docker-compose.yml        (Legado)"
echo ""
echo "├── 📁 scripts/"
echo "│   ├── setup.sh                  (Setup inicial)"
echo "│   ├── dev.sh                    (Desenvolvimento)"
echo "│   ├── deploy-aws.sh             (Deploy AWS)"
echo "│   └── backup.sh                 (Backup DB)"
echo ""
echo "├── 📁 data/                      (Criado automaticamente)"
echo "│   └── financeiro.db             (Banco SQLite)"
echo ""
echo "├── 📁 backups/                   (Criado automaticamente)"
echo "│   └── (backups do banco)"
echo ""
echo "├── docker-compose.yml            (Root - produção)"
echo "├── .env.docker                   (Root - config Docker)"
echo "├── .gitignore"
echo "├── README.md                     (Documentação completa)"
echo "├── QUICKSTART.md                 (Início rápido)"
echo "├── FEATURES.md                   (Features implementadas)"
echo "└── STRUCTURE.sh                  (Este arquivo)"
echo ""
echo "======================================================="
echo "📊 Estatísticas"
echo "======================================================="
echo ""
echo "Backend:"
echo "  • 6 Controladores"
echo "  • 6 Serviços de Negócio"
echo "  • 6 Rotas Modularizadas"
echo "  • 13 Tabelas de Banco de Dados"
echo "  • Autenticação JWT"
echo "  • Rate Limiting"
echo ""
echo "Frontend:"
echo "  • 5 Páginas Principais"
echo "  • 1 Context de Autenticação"
echo "  • 3 Componentes Base"
echo "  • Gráficos com Recharts"
echo "  • Styled com Tailwind CSS"
echo "  • Responsive Design"
echo ""
echo "Infraestrutura:"
echo "  • Docker & Docker Compose"
echo "  • 4 Scripts Bash"
echo "  • Pronto para AWS EC2"
echo "  • Backup Automatizado"
echo ""
echo "======================================================="
echo "🚀 Próximas Implementações Sugeridas"
echo "======================================================="
echo ""
echo "[ ] Admin Dashboard"
echo "[ ] Relatórios em PDF/CSV"
echo "[ ] Notificações por Email"
echo "[ ] Integração com Serviços de Pagamento"
echo "[ ] App Mobile (React Native)"
echo "[ ] Sistema de Alertas"
echo "[ ] Análise Preditiva"
echo "[ ] Integração com APIs de Bancos"
echo ""
